KSTVideo/Controllers/BasketController.cs
using KSTVideo.Models;
using KSTVideo.Services;
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace KSTVideo.Controllers
{
    public class BasketController : Controller
    {
        private string sessionkey = "";

       
        // GET: Basket
        public ActionResult Index()
        {
            //BasketView basket = GetBasket();
            var service = GetService();
            BasketView basket = new BasketView
            {
                BasketID = GetBasketID(),
                BasketLines = service.GetBasketItems(GetBasketID()),
                TotalCost = service.GetTotalCost(GetBasketID())
            };


            return View(basket);
        }

        public ActionResult Create(BasketItemCreate item)
        {
            return View();
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddToBasket(int id)
        {
            var service = GetService();
            BasketItemCreate basket = new BasketItemCreate
            {
                VideoID = id,
                BasketID = GetBasketID(),
                DateAdded = DateTime.Now
            };
           

            service.AddToBasket(basket);

            return RedirectToAction("Index");
        }


        
        public ActionResult PlaceOrder()
        {
            var service = GetService();
            BasketView basket = new BasketView
            {
                BasketID = GetBasketID(),
                BasketLines = service.GetBasketItems(GetBasketID()),
                TotalCost = service.GetTotalCost(GetBasketID())
            };

            service.SendEmail(basket);
            BasketView temp = basket;
            service.EmptyBasket(GetBasketID());

            return View(basket);
        }


        [HttpGet]
        [Route("RemoveBasketLine/{id}")]
        public ActionResult RemoveBasketLine(int id)
        {
            var service = GetService();
            service.RemoveBasketItem(GetBasketID(), id);
            return RedirectToAction("Index");
        }


        private string GetBasketID()
        {
            
            if (HttpContext.Session[sessionkey] == null)
            {
                if (!string.IsNullOrWhiteSpace(HttpContext.User.Identity.Name))
                {
                    HttpContext.Session[sessionkey] =
                    HttpContext.User.Identity.Name;
                }
                else
                {
                    Guid tempBasketID = Guid.NewGuid();
                    HttpContext.Session[sessionkey] = tempBasketID.ToString();
                }
            }
            return HttpContext.Session[sessionkey].ToString();
        }


        private BasketView GetBasket()
        {
            BasketView basket = (BasketView)Session["basket"];
            if (basket is null)
            {
                var service = GetService();
                basket = new BasketView
                {
                    BasketID = GetBasketID(),
                    BasketLines = service.GetBasketItems(GetBasketID()),
                    TotalCost = service.GetTotalCost(GetBasketID())
                };
               
            }

            Session["basket"] = basket;
            return basket;
        }


        private BasketService GetService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new BasketService(userId);
            return service;
        }



    }
}

KSTVideo/Controllers/VideosController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using KSTVideo.Data;
using KSTVideo.Models;
using KSTVideo.Services;
using Microsoft.AspNet.Identity;

namespace KSTVideo.Controllers
{
    [Authorize]
    public class VideosController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

       

        // GET: Videos
        public ActionResult Index(string genre,string search)
        {

            var service = GetService();
            var videos = service.GetVideos(genre,search);
            if(!String.IsNullOrEmpty(search))
            {
                ViewBag.Search = search;
            }

            var genres = db.Videos.OrderBy(v => v.Genre.Name).Select(v =>
            v.Genre.Name).Distinct();

            ViewBag.Genre = new SelectList(genres);
            return View(videos);
        }

        // GET: Videos/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var service = GetService();

            VideoDetail video = service.GetVideoById(id);
           
            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // GET: Videos/Create
        public ActionResult Create()
        {
            ViewBag.GenreID = new SelectList(db.Genres, "ID", "Name");
            ViewBag.ImageName = new SelectList(db.VideoImages, "ImageName", "ImageName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VideoCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = GetService();

            service.CreateVideo(model);

            return RedirectToAction("Index");
        }

        

        // GET: Videos/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var service = GetService();

            VideoDetail video = service.GetVideoById(id);

            if (video == null)
            {
                return HttpNotFound();
            }
            ViewBag.GenreID = new SelectList(db.Genres, "ID", "Name", video.GenreID);
            return View(video);
        }




        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, VideoUpdate model)
        {
            if (!ModelState.IsValid) return View(model);

            if (model.ID != id)
            {
                ModelState.AddModelError("", "Id Mismatch");
                return View(model);
            }

            var service = GetService();

            if (service.UpdateVideo(model))
            {
                TempData["SaveResult"] = "Your video was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "Your video could not be updated.");
            return View(model);
        }

       

        // GET: Videos/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var service = GetService();
            var video = service.GetVideoById(id);

            if (video == null)
            {
                return HttpNotFound();
            }
            return View(video);
        }

        // POST: Videos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            var service = GetService();
            service.DeleteVideo(id);
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }


        private VideoService GetService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new VideoService(userId);
            return service;
        }
    }
}

KSTVideo/Views/Videos/Create.cshtml
@model KSTVideo.Models.VideoCreate

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>Video</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
        </div>
    </div>



    <div class="form-group">
        @Html.LabelFor(model => model.UPCcode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.UPCcode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.UPCcode, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.ImageName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ImageName", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ImageName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.RentalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.RentalPrice, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.RentalPrice, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Create" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KSTVideo/Views/Videos/Delete.cshtml
@model KSTVideo.Models.VideoDetail

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Video</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UPCcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UPCcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentalPrice)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

KSTVideo/Views/Videos/Details.cshtml
@model KSTVideo.Models.VideoDetail

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Video</h4>
    <hr />
    <img src="@Url.Content("~/Content/Images/" + Model.ImageName)" />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Genre.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.UPCcode)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.UPCcode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.RentalPrice)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.RentalPrice)
        </dd>


        <dt>
            @using (Html.BeginForm("AddToBasket", "Basket"))
            {
                @Html.AntiForgeryToken()
                @Html.HiddenFor(model => model.ID)

                <input type="submit" class="btn btn-primary btn-xs" value="Add to Basket">
            }
        </dt>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

KSTVideo/Views/Videos/Edit.cshtml
@model KSTVideo.Models.VideoDetail

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Video</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.UPCcode, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UPCcode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UPCcode, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.RentalPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.RentalPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.RentalPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.GenreID, "GenreID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("GenreID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.GenreID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

KSTVideo/Views/Videos/Index.cshtml
@model IEnumerable<KSTVideo.Data.Video>


@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
    @using (Html.BeginForm("Index", "Videos", FormMethod.Get))
    {
        <label>Filter by genre:</label> @Html.DropDownList("Genre", "All")
        <input type="submit" value="Filter" />
        <input type="hidden" name="Search" id="Search" value="@ViewBag.Search" />
    }
    </p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ImageName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Genre.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Description)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.UPCcode)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.RentalPrice)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
<tr>
    <td>
        <img src="@Url.Content("~/Content/Images/" + item.ImageName)" />
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Genre.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Name)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Description)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.UPCcode)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.RentalPrice)
    </td>
    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID })
    </td>
</tr>
}

</table>